export const ActionTypes = {
    SET_MAX_SPEED: 'SET_MAX_SPEED',
    SET_NUM_OF_NODES: 'SET_NUM_OF_NODES',
    SET_POPULATION_SIZE: 'SET_POPULATION_SIZE',
    SET_MUTATION_PROBABILITY: 'SET_MUTATION_PROBABILITY',
    SET_GRAPH_MATRIX: 'SET_GRAPH_MATRIX',
    SET_START_POINT: 'SET_START_POINT',
    SET_END_POINT: 'SET_END_POINT',
    SET_POPULATION: 'SET_POPULATION',
};
